### ISSUE TITLE
import accounts into static marketing lists

### ISSUE THREAD

**Issue by yunjie-yao** [tcorcor1/MarketingListImporter.TyCorcoran#1]
Now only supported leads or contacts .
Have you considered supporting other entities, such as account?

**Comment by tcorcor1** [comment]
I considered it but decided not to move forward. A tool like this works well with Contacts and Leads because I can count on the email address being unique and therefore know exactly when to create a new Lead/Contact vs. merge an existing into the list.

From what I have seen over the years emailaddress1 on the Account is much less reliable. Sometimes it's blank or using a generic mailbox, etc. I didn't want to include Accounts because I think it may produce unexpected results for some users.
