### ISSUE TITLE
Import Contact .csv file fails

### ISSUE THREAD

**Issue by nilsvanbever** [tcorcor1/MarketingListImporter.TyCorcoran#2]
<img width="329" alt="ErrorXRMToolbox" src="https://user-images.githubusercontent.com/92519438/137301447-506af832-ec8d-4058-84d0-ae80848318f9.PNG">

Fails when importing the .csv file on FirstName the tool gives back an error. We've tried every possible option, but still receive an error. Even if I import a empty .csv file.

**Comment by tcorcor1** [comment]
Sorry to hear that you are having issue with the tool. I have just tested 3 imports and unfortunately am not able to recreate this issue.

**Comment by tcorcor1** [comment]
Hello,

I noticed that you haven't responded to my question over email so I will be proceeding to close this issue since I am unable to recreate the problem on my side.

I would recommend creating your own import template and trying to reimport your data. My suspicion is that this may be a csv parsing issue where your data is input using semi-colons as delimiters while the import template uses commas in the header as a delimiter. 

As long as schema names are the same, data will be mapped appropriately and by you creating the template the appropriate csv delimiters will be applied based off your OS CultureInfo.

I hope you give it a try. Sorry again you are experiencing an issue. Hopefully creating your own template can resolve the issue.
